name: Approve Preprod PRs
on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: filip/ga_automated_pr
      - name: View PR Author
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."
      - name: approve-pr
        if: ${{ github.head_ref == 'filip/ga_automated_pr' }}
        run: |
          gh pr review --approve
