on:
  push:
    branches:
      - filip/*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: rebase main
      #   run: |
      #     git remote -v
      #     git fetch
      #     git checkout ${{ github.ref.name }}
      #     git rebase origin/main
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'Pulling ${{ github.ref }} into main'
          pr_body: '*An automated PR*'
      - name: some-tests
        run: |
          exit 1
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
